CREATE TABLE users (
    id VARCHAR(255) PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    photo_link VARCHAR(255),
    faculty VARCHAR(255) NOT NULL,
    bio VARCHAR(250) NOT NULL,
    date_joined TIMESTAMP NOT NULL,
    active BOOLEAN DEFAULT TRUE,
    comments INTEGER DEFAULT 0,
    posts INTEGER DEFAULT 0,
    expired BOOLEAN DEFAULT FALSE,
    locked BOOLEAN DEFAULT FALSE
);

CREATE TABLE users_active_in (
    user_id VARCHAR(255) NOT NULL,
    active_in VARCHAR(255),
    CONSTRAINT fk_users_active_in_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
);

CREATE TABLE users_authorities (
    user_id VARCHAR(255) NOT NULL,
    authorities VARCHAR(255),
    CONSTRAINT fk_users_authorities_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
);

CREATE TABLE resources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255),
    course VARCHAR(255),
    uploader VARCHAR(255),
    uploaded_at TIMESTAMP WITH TIME ZONE,
    download_url VARCHAR(255)
);