# ── Server ────────────────────────────────────
server.port=8080

# ── Database ──────────────────────────────────
spring.datasource.url=jdbc:postgresql://localhost:5432/CCWebsite
spring.datasource.username=postgres
spring.datasource.password=Admin123&
spring.datasource.driver-class-name=org.postgresql.Driver

# ── JPA / Hibernate ───────────────────────────
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ── Security (dev credentials — change for production)
spring.security.user.name=admin
spring.security.user.password=secret

# ── JWT ──────────────────────────────────
spring.jwt.secret.access=7bf22b25903f86f5077c5bf914701eb3f2438f125e52ae470847bca3b43712d0
spring.jwt.secret.refresh=7bf22b25903f86f5077c5bf914701eb3f2438f125e52ae470847bca3b43712d0
spring.jwt.access.expiration=3600000
spring.jwt.refresh.expiration=4600000
